spring:
  application:
    name: spring-boot-clean-architecture
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bankdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
