spring:
  application:
    name: spring-webflux-hexagonal-architecture
  r2dbc:
    url: r2dbc:h2:mem:///coffeedb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
